aboutme/urls.py
from django.urls import path

from .views import AboutmeListView

app_name = 'aboutme'

urlpatterns = [
    path("", AboutmeListView.as_view(), name="aboutme"),
]

contact/urls.py
from django.urls import path

from contact.views import contactme

# from contact.views import SocialLinksListView

app_name = 'contact'

urlpatterns = [
    # path("", SocialLinksListView.as_view(), name="contact"),
    path("", contactme, name='contact'),

]

hobby/urls.py
from django.urls import path

from .views import HobbyListView

app_name = 'hobby'

urlpatterns = [
    path("", HobbyListView.as_view(), name="all_hobbys"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('projects/', include('projects.urls')),
    path('hobby/', include('hobby.urls')),
    path('aboutme/', include('aboutme.urls')),
    path('contact/', include('contact.urls')),
    path('tinymce/', include('tinymce.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path

from .views import ProjectsListView, CategoryProjectListView, ProjectDetailView

app_name = 'projects'

urlpatterns = [
    path("", ProjectsListView.as_view(), name="all_projects"),
    path('category/<slug:slug>/', CategoryProjectListView.as_view(), name='category_projects_list'),
    path('<int:pk>/<slug:slug>', ProjectDetailView.as_view(), name='project_detail'),
]

website/urls.py
from django.urls import path
from website.views import Home

app_name = 'website'

urlpatterns = [
    path("", Home.as_view(), name="home"),
]

website/views.py
from django.shortcuts import render
from django.views import View


class Home(View):
    template_name = "website/home.html"

    def get(self, request):
        return render(request, self.template_name, {})

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/f558545230.js" crossorigin="anonymous"></script>

    {% block css %}{% endblock %}

    <title>{% block title %}{% endblock %}</title>
</head>

<body>
{% include 'website/navbar.html' %}
{% block body %}{% endblock %}

{% include 'website/footer.html' %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

{% block scripts %}{% endblock %}

</body>
</html>

website/templates/website/footer.html
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/web/style.css' %}"> {% endblock %}

<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-6 col-sm-7 col-md-9">
                <div class="footer-topic">INFO</div>
                <p class="text-justify">Projekt pełni rolę <i> PERSONALNEGO PORTFOLIO </i>.<br>
                    Użyte narzędzia: Django, HTML, CSS, JS, Bootstrap</p><br>
            </div>
            <div class="col-6 col-sm-5 col-md-3">
                <div class="footer-menu">
                    <div class="footer-topic">MENU</div>
                    <ul class="footer-links">
                        <li><a href="{% url 'aboutme:aboutme' %}">O mnie</a></li>
                        <li><a href="{% url 'projects:all_projects' %}">Pojekty</a></li>
                        <li><a href="{% url 'hobby:all_hobbys' %}">Hobby</a></li>
                        <li><a href="{% url 'contact:contact' %}">Kontakt</a></li>
                    </ul>
                </div>
            </div>
            <div class="copyright col-12">2020 &copy; Wszystkie prawa zastrzeżone dla
                <a href='{% url 'website:home' %}'><i>Łukasz Chaliński</i></a>.
            </div>
        </div>
    </div>
</footer>

website/templates/website/home.html
{% extends "website/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/web/style.css' %}"> {% endblock %}
{% block title %}HOME{% endblock %}


{% block body %}
    <div class="site-main">
        <div class="site-banner">

            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-12 site-title">
                        <h3 class="title-text">Cześć</h3>
                        <h1 class="title-text">jestem Łukasz</h1>
                        <h4 class="title-text text-uppercase">Junior Python Developer</h4>

                        <div class="site-button">
                            <div class="d-flex flex-row flex-wrap">
                                <a href="{% url 'contact:contact' %}"><button type="button" class="btn btn-outline-secondary mr-4 text-uppercase">Zatrudnij mnie
                                </button></a>


                                <a href="{% static 'files/cv.pdf' %}" download="CV"><button type="button" class="btn btn-outline-secondary mr-4 text-uppercase"><i class="far fa-arrow-alt-circle-down"></i> Pobierz CV
                                </button></a>



                            </div>

                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 banner-img">
                        <img class="img-fluid"
                             src="{% static 'images/lukasz-chalinski.jpg' %}" alt="Photo"><br>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

website/templates/website/navbar.html
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/web/style.css' %}"> {% endblock %}

{#todo W PRZYSZŁOŚCI ZMIENIĆ Z BOOTSTRAPA NA COŚ KONKRETNIEJSZEGO#}


<nav class='navbar navbar-expand-md navbar-light bg-white absolute-top'>
    <div class='container'>

        <button class='navbar-toggler order-2 order-md-1' type='button' data-toggle='collapse' data-target='#navbar'
                aria-controls='navbar' aria-expanded='false' aria-label='Toggle navigation'>
            <span class='navbar-toggler-icon'></span>
        </button>

        <a class='navbar-brand mx-auto order-1 order-md-1' href='{% url 'website:home' %}'>łukasz_chaliński</a>

        <div class='collapse navbar-collapse order-4 order-md-4' id='navbar'>
            <ul class='navbar-nav ml-auto'>

                <li class='nav-item'>
                    <a class='nav-link' href='{% url 'website:home' %}'>HOME</a>
                </li>

                <li class='nav-item'>
                    <a class='nav-link' href='{% url 'aboutme:aboutme' %}'>O MNIE</a>
                </li>

                <li class='nav-item'>
                    <a class='nav-link' href='{% url 'projects:all_projects' %}'>PROJEKTY</a>
                </li>

                <li class='nav-item'>
                    <a class='nav-link' href='{% url 'hobby:all_hobbys' %}'>HOBBY</a>
                </li>

                <li class='nav-item'>
                    <a class='nav-link' href='{% url 'contact:contact' %}'>KONTAKT</a>
                </li>
            </ul>
        </div>
    </div>
</nav>