hobby/urls.py
from django.urls import path

from .views import HobbyListView

app_name = 'hobby'

urlpatterns = [
    path("", HobbyListView.as_view(), name="all_hobbys"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('projects/', include('projects.urls')),
    path('hobby/', include('hobby.urls')),
    path('aboutme/', include('aboutme.urls')),
    path('contact/', include('contact.urls')),
    path('tinymce/', include('tinymce.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path

from .views import ProjectsListView, CategoryProjectListView, ProjectDetailView

app_name = 'projects'

urlpatterns = [
    path("", ProjectsListView.as_view(), name="all_projects"),
    path('category/<slug:slug>/', CategoryProjectListView.as_view(), name='category_projects_list'),
    path('<int:pk>/<slug:slug>', ProjectDetailView.as_view(), name='project_detail'),
]

projects/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from tinymce.models import HTMLField


class ProjectCategory(models.Model):
    tool_name = models.CharField(max_length=128)
    tool_image = models.ImageField(blank=False, null=False, upload_to='tool_image/')
    slug = models.SlugField(null=False, unique=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.tool_name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.tool_name

    class Meta:
        verbose_name_plural = 'Project categories'


class Project(models.Model):
    title = models.CharField(max_length=120)
    category = models.ManyToManyField(ProjectCategory, related_name='projects')
    snippet = models.TextField(max_length=500, null=False)
    body = HTMLField(max_length=1500, null=False)
    github_repository = models.URLField(max_length=200)
    image = models.ImageField(blank=False, null=False, upload_to='project_image/')
    image2 = models.ImageField(blank=False, null=False, upload_to='project_image/')
    image3 = models.ImageField(blank=False, null=False, upload_to='project_image/')

    slug = models.SlugField(null=False, unique=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def project_categories(self):
        return ", \n".join([x.tool_name for x in self.category.all()])

    def get_absolute_url(self):
        return reverse('projects:project_detail', kwargs={'pk': self.pk, 'slug': self.slug})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Projects'

projects/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from projects.models import Project, ProjectCategory

app_name = 'projects'


class ProjectsListView(ListView):
    template_name = "projects/all_projects.html"
    model = Project

    def get_queryset(self):
        return self.model.objects.all().order_by('-pk')


class CategoryProjectListView(ListView):
    template_name = "projects/project_category.html"
    queryset = Project.objects.order_by('-pk')

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(
            category__slug=self.kwargs['slug'])

    def projectcategory(self):
        return get_object_or_404(ProjectCategory, slug=self.kwargs['slug'])


class ProjectDetailView(DetailView):
    template_name = "projects/project_detail.html"
    model = Project

projects/templates/projects/all_projects.html
{% extends "website/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/projects/style.css' %}"> {% endblock %}
{% block title %}WSZYSTKIE PROJEKTY{% endblock %}


{% block body %}

    <div class="page_title"> WSZYSTKIE PROJEKTY</div>

    {% include 'projects/project_list_base.html' %}

{% endblock %}

projects/templates/projects/project_category.html
{% extends "website/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/projects/style.css' %}"> {% endblock %}
{% block title %}  KATEGORIA PROJEKTU: {{ view.projectcategory.tool_name }}  {% endblock %}

{% block body %}

    <div class="page_title"> KATEGORIA PROJEKTU: {{ view.projectcategory.tool_name|upper }}</div>

    {% include 'projects/project_list_base.html' %}

{% endblock %}

projects/templates/projects/project_detail.html
{% extends "website/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/projects/style.css' %}"> {% endblock %}

{% block title %} SZCZEGÓŁY PROJEKTU {{ project.title|upper }}{% endblock %}


{% block body %}

    <div class="page_title"> SZCZEGÓŁY PROJEKTU</div>

    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="project-banner">
                    <div class="project-det-title">
                        {{ project.title }}
                    </div>
                </div>
                <div class="project-det-body">
                    {{ project.body|safe }}
                </div>
            </div>
            <div class="col-md-5 col-sm-12 col-12">

                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="{{ project.image.url }}" alt="First slide">
                            <div class="carousel-caption d-none d-md-block">
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="{{ project.image2.url }}" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="{{ project.image3.url }}" alt="Third slide">
                        </div>
                    </div>


                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                </div>
            </div>
            <div class="project-tool col-md-6">
                <div class="tool-title">
                    Wykorzystane technologie i narzędzia
                </div>
                <div class="project-category">
                    {% for category in project.category.iterator %}
                        <a href="{% url 'projects:category_projects_list' category.slug %}">
                            <img src="{{ category.tool_image.url }}"/> </a>
                    {% endfor %}
                </div>
            </div>


            <div class="project-github col-md-6">
                <div class="repo-title">
                    <i class="fab fa-github"></i> github
                </div>

                <div class="git-link">

                    <a href="{{ project.github_repository }}" target="_blank"> {{ project.github_repository }}</a>
                </div>
            </div>


        </div>


    </div>


    </div>







{% endblock %}

projects/templates/projects/project_list_base.html
<div class="col-lg-12 text-center projects-title">
{#    <p class="para">#}
{#        Tutaj będzie znajdował się krótki opis wszystkich moich projektów.#}
{#    </p>#}
</div>
<br>
<div class="container all-projects">
    <div class="row">
        {% if object_list %}
            {% for project in object_list %}
                <div class="col12 col-sm-4">
                    <div class="card">
                        <a class="img-card"
                           href="{{ project.get_absolute_url }}">
                            <img src="{{ project.image.url }}"/>
                        </a>
                        <div class="card-content">
                            <div class="card-title">
                                <a href="{{ project.get_absolute_url }}">
                                    {{ project.title }}
                                </a>
                            </div>
                            <p class="snippet">
                                {{ project.snippet }}
                            </p>
                        </div>
                        <div class="card-category">
                            {% for category in project.category.iterator %}
                                <a href="{% url 'projects:category_projects_list' category.slug %}">
                                    <img src="{{ category.tool_image.url }}"/> </a>
                            {% endfor %}
                        </div>
                        <div class="card-read-more">
                            <a href="{{ project.get_absolute_url }}">
                                szczegóły
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>